### ISSUE TITLE
collision of the enemies

### ISSUE THREAD

**Issue by klwaamzhang** [earldenzel/Paranorm_Phantos#1]
It's hard to avoid the bats and the ghosts.
The collisions of enemies may need to be smaller than the assets themselves.

**Comment by klwaamzhang** [comment]
If I knock back the zombie, the zombie will be stuck into the barrier.

**Comment by earldenzel** [comment]
the collision of the enemies weren't proper. fixed the monster collision on this commit. please check of it is still difficult to avoid bats.
